/** Estilos do painel admin (compartilhados entre as seções). */
export const s: Record<string, React.CSSProperties> = {
  pagina: { minHeight: "100vh", background: "#171717", color: "#F1E7D2", padding: "24px 20px 60px", fontFamily: "system-ui, sans-serif" },
  topo: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24, maxWidth: 1100, marginInline: "auto" },
  h1: { margin: 0, fontSize: 22 },
  h2: { margin: "0 0 4px", fontSize: 17, color: "#D5A62A" },
  legenda: { margin: "0 0 16px", fontSize: 13, opacity: 0.8 },
  botaoSair: { background: "transparent", border: "1px solid #F1E7D2", color: "#F1E7D2", borderRadius: 8, padding: "6px 14px", cursor: "pointer" },
  aviso: { maxWidth: 1100, marginInline: "auto", background: "#17352B", color: "#fff", padding: "8px 14px", borderRadius: 8, marginBottom: 16, fontSize: 14 },
  avisoErro: { maxWidth: 1100, marginInline: "auto", background: "#B84A32", color: "#fff", padding: "8px 14px", borderRadius: 8, marginBottom: 16, fontSize: 14 },
  secao: { maxWidth: 1100, marginInline: "auto", background: "#1f1f1f", borderRadius: 12, padding: 20, marginBottom: 20 },
  gridConfig: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 12, alignItems: "end" },
  gridNova: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 12, alignItems: "end" },
  campo: { display: "flex", flexDirection: "column", gap: 4, fontSize: 13 },
  input: { padding: "8px 10px", borderRadius: 6, border: "1px solid #444", background: "#111", color: "#F1E7D2" },
  botaoSalvar: { gridColumn: "1 / -1", background: "#B84A32", color: "#fff", border: "none", borderRadius: 8, padding: "10px 16px", cursor: "pointer", fontWeight: 600, marginTop: 4 },
  tabela: { width: "100%", borderCollapse: "collapse", fontSize: 13 },
  th: { textAlign: "left", padding: "8px 10px", borderBottom: "1px solid #444", color: "#D5A62A" },
  td: { padding: "8px 10px", borderBottom: "1px solid #2a2a2a" },
  inputCelula: { width: "100%", padding: "4px 6px", borderRadius: 4, border: "1px solid #444", background: "#111", color: "#F1E7D2", fontSize: 13 },
  botaoMini: { background: "#17352B", color: "#fff", border: "none", borderRadius: 6, padding: "4px 10px", marginRight: 6, cursor: "pointer", fontSize: 12 },
  botaoMiniOutline: { background: "transparent", color: "#F1E7D2", border: "1px solid #666", borderRadius: 6, padding: "4px 10px", marginRight: 6, cursor: "pointer", fontSize: 12 },
  botaoMiniPerigo: { background: "transparent", color: "#B84A32", border: "1px solid #B84A32", borderRadius: 6, padding: "4px 10px", cursor: "pointer", fontSize: 12 },
  gridMapa: { display: "flex", flexWrap: "wrap", gap: 20, marginTop: 20, alignItems: "flex-start" },
  colunaMapa: { flex: "2 1 420px", minWidth: 0 },
  cartao: { flex: "1 1 220px", background: "#111", border: "1px solid #333", borderRadius: 10, padding: 16 },
  selo: { display: "inline-block", borderRadius: 999, padding: "2px 10px", fontSize: 12, fontWeight: 600 },
};
